### ISSUE TITLE
Short Bio 

### ISSUE THREAD

**Issue by Xanthylajoie** [brainhack-school2022/Lajoie_project#1]
Hello Hellooo
Je m'appelle Xanthy et je passe la moitié de mes conversations à épeler mon nom mais ça me fais toujours plaisir, j'suis rendu une pro.  Je suis étudiante au PhD en neurosciences cognitives et computationnelles à l'Université de Montréal et je me concentre sur les différences entre les sexes dans le réseau fonctionnel du langage. En gros, on veut savoir si les régions impliqués et la force de connectivité entre elles diffèrent entre les hommes et les femmes.

Appart la science et l'école, je suis une passionnée de bouffe, de camping, de randonnée (pas 14km quand même), de peinture et de photographie. J'haie le vélo, c'est trop forçant et j'suis raqué pour 2 jours après, bref le pire moyen de transport. Par contre, un vélo tandem pourrait m'intéresser

**Comment by complexbrains** [comment]
Loved it! Very honest! 😍 

Thank you! 🚀
